// Generated by https://quicktype.io

export interface User {
    uid: string;
    email: string;
    emailVerified: boolean;
    displayName: string;
    dateCreated: string;
    dateEdited: string;
    lastLogIn: string;
    actived: boolean;
}

export interface Document {
    uid: string;
    name: string;
    type: string;
    subType: string;
    description: string;
    dateCreated: string;
    dateEdited: string;
    actived: boolean;
}